image: maven:3-jdk-11

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  LONG_RUNNING_TESTS: "true"

cache:
  paths:
    - .m2/repository/
    - target/

pipeline:
  stage: build
  script:
    - mvn test
  only:
    - merge_requests
    - master