global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: queue_monitoring
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9091